server {
    listen 80;
    server_name 103.143.142.245;

    location = / {
        return 301 /baking/;
    }

    location ^~ /baking {
        add_header X-My-Baking "yes";
        root /var/www/muka_baking/frontend/dist;
        try_files $uri $uri/ /baking/index.html;
    }

    location /api/ {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /uploads/ {
        proxy_pass http://localhost:5000/uploads/;
    }
}
