export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  PROGRAM: '/program',
  RECEIPT: '/receipt',
  CONTACT: '/contact',
  AUTH: '/auth',
  CHIEFS: '/chiefs',
  CHIEF_DETAIL: (id) => `/chief/${id}`,
  CHIEF_DETAIL_PATTERN: '/chief/:id',
  PROGRAM_DETAIL: (slug) => `/program/${slug}`,
  PROGRAM_DETAIL_PATTERN: '/program/:slug',
  POST_DETAIL: (slug) => `/post/${slug}`,
  POST_DETAIL_PATTERN: '/post/:slug',
  MY_ACCOUNT: '/my-account',
  ADMIN: '/admin',
  ADMIN_POST_NEW: '/admin/post/new',
  ADMIN_POST_EDIT: (id) => `/admin/post/edit/${id}`,
  ADMIN_POST_EDIT_PATTERN: '/admin/post/edit/:id',
  ADMIN_PROGRAM_NEW: '/admin/program/new',
  ADMIN_PROGRAM_EDIT: (id) => `/admin/program/edit/${id}`,
  ADMIN_PROGRAM_EDIT_PATTERN: '/admin/program/edit/:id',
};
